apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: clean-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: /clean
          backend:
            serviceName: clean-service
            servicePort: 8080