apiVersion: networking.k8s.io/v1beta1
  kind: Ingress
  metadata:
    name: clean-ingress
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /
  spec:
    rules:
      - http:
          paths:
            - path: /test
              backend:
                serviceName: clean-service
                servicePort: 80
